compilation:
  cloud_properties: {}
  network: efs-net
  workers: 1
director_uuid: 17a45148-1d00-43bc-af28-9882e5a6535a
jobs:
- instances: 1
  log_level: debug
  name: pats-broker
  networks:
  - name: efs-net
  properties:
    efsbroker:
      data-dir: /var/vcap/store/pats-efsbroker
      password: admin
      plan-id: pats-plan-id
      plan-name: efs-plan
      service-id: pats-efs-volume
      service-name: efs-service
      username: admin
    route_registrar:
      routes:
      - name: pats-broker
        port: 8999
        registration_interval: 20s
        tags:
          component: pats-broker
        uris:
        - pats-broker.bosh-lite.com
  resource_pool: efs-resourcepool
  templates:
  - name: efsbroker
    release: efs-volume
  - name: route_registrar
    release: cf
- instances: 1
  log_level: debug
  name: efsbroker
  networks:
  - name: efs-net
  properties:
    efsbroker:
      plan-id: free
      plan-name: free-efs-disk
      service-id: efs-volume
      service-name: efs-volume
    route_registrar:
      routes:
      - name: efsbroker
        port: 8999
        registration_interval: 20s
        tags:
          component: efsbroker
        uris:
        - efsbroker.bosh-lite.com
  resource_pool: efs-resourcepool
  templates:
  - name: efsbroker
    release: efs-volume
  - name: route_registrar
    release: cf
name: efs-volume
networks:
- name: efs-net
  subnets:
  - cloud_properties: {}
    gateway: 10.244.9.1
    range: 10.244.9.0/24
    static:
    - 10.244.9.2
  type: manual
properties:
  efsbroker:
    plan-desc: free efs volume for bosh-lite
  nats:
    machines:
    - 10.244.0.6
    password: nats
    port: 4222
    user: nats
releases:
- name: efs-volume
  version: latest
- name: cf
  version: latest
resource_pools:
- cloud_properties: {}
  name: efs-resourcepool
  network: efs-net
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
update:
  canaries: 1
  canary_watch_time: 1000-60000
  max_in_flight: 3
  serial: false
  update_watch_time: 1000-60000

