---
name: local-volume
director_uuid:  (( merge ))
compilation:
  workers: 1
  network: efsvolume-subnet
  reuse_compilation_vms: true
  cloud_properties:
    availability_zone: us-east-1c
    instance_type: m3.large
    ephemeral_disk:
      size: 10000 # in MB
      type: gp2
jobs:
- name: efsbroker-pats
  instances: 1
  log_level: debug
  networks:
  - name: efsvolume-subnet
    default: [dns, gateway]
  - name: public
    static_ips: [52.205.244.140]
  resource_pool: medium
  templates:
  - release: efs-volume
    name: efsbroker
  - release: cf
    name: route_registrar
  persistent_disk: 25000
  properties:
    efsbroker:
      service-id: efsvolume-ginkgoPATS-pats-efs-volume
      service-name: efsvolume-ginkgoPATS-pats-service
      plan-name: efsvolume-ginkgoPATS-pats-plan
      plan-id: efsvolume-ginkgoPATS-pats-plan-id
      data-dir: /var/vcap/store/pats-efsbroker
      username: (( merge ))
      password: (( merge ))
    route_registrar:
      routes:
      - name: pats-efs-broker
        port: 8999
        registration_interval: 20s
        tags:
          component: pats-efs-broker
        uris:
        - pats-broker.efsvolume-ginkgoPATS.persi.cf-app.com


- name: efsbroker-acc
  instances: 1
  log_level: debug
  networks:
  - name: efsvolume-subnet
    default: [dns, gateway]
  - name: public
    static_ips: [52.205.231.171]
  resource_pool: medium
  templates:
  - release: efs-volume
    name: efsbroker
  - release: cf
    name: route_registrar
  persistent_disk: 25000
  properties:
    efsbroker:
      service-id: efs-volume
      service-name: efs-volume
      plan-name: free-efs-dist
      plan-id: free
      data-dir: /var/vcap/store/pats-efsbroker
    route_registrar:
      routes:
      - name: efs-broker
        port: 8999
        registration_interval: 20s
        tags:
          component: efs-broker
        uris:
        - efs-broker.persi.cf-app.com

networks:
- name: efsvolume-subnet
  subnets:
  - cloud_properties:
      security_groups:
      - sg-a2945ad9
      subnet: subnet-8c2365d4
    dns:
    - 10.10.0.2
    gateway: 10.10.200.1
    range: 10.10.200.0/24
    reserved:
    - 10.10.200.2 - 10.10.200.9
    - 10.10.200.106 - 10.10.200.110
    static:
    - 10.10.200.10 - 10.10.200.105
  type: manual
- name: public
  type: vip
properties:
  efsbroker:
    plan-desc: efs filesystem for aws
    efsdriver-url: (( merge ))
  nats: (( merge ))
releases:
  - name: efs-volume
    version: latest
  - name: cf
    version: latest
resource_pools:
  - name: large
    network: efsvolume-subnet
    stemcell:
      name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
      version: latest
    cloud_properties:
      instance_type: m3.large
      availability_zone: us-east-1c

  - name: medium
    network: efsvolume-subnet
    stemcell:
      name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
      version: latest
    cloud_properties:
      instance_type: m3.medium
      availability_zone: us-east-1c
update:
  canaries: 1
  max_in_flight: 3
  serial: false
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
